<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Timothy D Meadows II</Authors>
    <Description>An elliptic curve offering 128 bits of security and designed for use with the elliptic curve Diffie–Hellman (ECDH) key agreement scheme. It is one of the fastest ECC curves and is not covered by any known patents.</Description>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/TimothyMeadows/Curve25519.NetCore</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TimothyMeadows/Curve25519.NetCore</RepositoryUrl>
    <RepositoryType>Github</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SecureRandom.NetCore" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
